services:
  orders:
    build:
      context: .
      dockerfile: ./apps/driver/Dockerfile
      target: development
    command: npm run start:dev driver
    env_file:
      - ./.env
    # depends_on:
    #   - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'
